-- 1. SELECT ALL PEOPLE WITH AGES BETWEEN 30 AND 35
SELECT * FROM people WHERE age BETWEEN 30 AND 35;

-- 2. SELECT ALL PEOPLE WITH AGES BETWEEN 30 AND 35 OR WITH ANY AGE BUT ARE FROM “Miami”
SELECT * FROM people WHERE age BETWEEN 30 AND 35 OR city = 'Miami';

-- 3. SELECT ALL PEOPLE WHOSE NAME STARTS WITH “A”
SELECT * FROM people WHERE name LIKE 'A%';

-- 4. SELECT ALL PEOPLE THAT HAVE AT LEAST AN “A” IN THEIR NAME AND ARE 18 OR OLDER
SELECT * FROM people WHERE name LIKE '%A%' AND age >= 18;

-- 5. SELECT ALL PEOPLE THAT LIVE IN ANY CITY THAT HAS 5 LETTERS
SELECT * FROM people WHERE length(city) = 5;

-- 6. SELECT ONLY THE LAST 3 PEOPLE OF THE TABLE (WHEN ORDERED ALPHABETICALLY BY NAME)
SELECT * FROM people ORDER BY name DESC LIMIT 3;

-- 7. HOW MANY ARE FROM “New York”
SELECT COUNT(*) AS newyork_people FROM people WHERE city = 'New York';

-- 8. SELECT ALL PEOPLE AND ADD AN EXTRA COLUMN TO YOUR SELECT THAT DISPLAYS “Adult” IF THE PERSON IS 18 OR OLDER OTHERWISE “Child”
SELECT *, IF(age IS NULL, 'No age specified', IF(age >= 18, 'Adult', 'Child')) AS age_groups FROM people;

-- 9. SAME AS BEFORE, BUT NOW ADD “Senior” AS WELL IF SOMEONE IS OVER 65
SELECT *, IF(age IS NULL, 'No age specified', IF(age < 18, 'Child', IF(age > 65, 'Senior', 'Adult'))) AS age_groups FROM people;

-- 10. SELECT city WHERE 2 OR MORE PEOPLE LIVE
SELECT city, IF(city IS NULL, 'No city specified', COUNT(name)) AS city_with_atleast_twopeople FROM people GROUP BY city HAVING COUNT(name) >= 2;

-- 11. SELECT ALL PEOPLE WHERE BOTH age AND city ARE NULL
SELECT * FROM people WHERE age IS NULL AND city IS NULL;
